# Allow kube-rbac-proxies to create tokenreviews to check Prometheus identity when scraping metrics.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-kube-rbac-proxy-binding
subjects:
  - kind: ServiceAccount
    name: aws-efs-csi-driver-controller-sa
    namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: efs-kube-rbac-proxy-role
  apiGroup: rbac.authorization.k8s.io
