apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: aws-efs-csi-driver-operator.v4.9.0
  namespace: placeholder
  annotations:
    # This example is useless, because the operator does not have its own CRD, OCP console won't offer it as a CR.
    alm-examples: |-
      [
        {
          "apiVersion": "operator.openshift.io/v1",
          "kind": "ClusterCSIDriver",
          "metadata": {
            "name": "efs.csi.aws.com"
          },
          "spec": {
            "logLevel": "Normal",
            "managementState": "Managed",
            "operatorLogLevel": "Normal"
          }
        }
      ]
    categories: Storage
    "operatorframework.io/suggested-namespace": openshift-cluster-csi-drivers
    capabilities: Full Lifecycle
    containerImage: quay.io/openshift/origin-aws-efs-csi-driver-operator:latest
    support: Red Hat
    repository: https://github.com/openshift/aws-efs-csi-driver-operator
    createdAt: "2021-07-14T00:00:00Z"
    description: Install and configure AWS EFS CSI driver.
    olm.skipRange: ">=4.3.0 <4.9.0"
  labels:
    operator-metering: "true"
    "operatorframework.io/arch.amd64": supported
spec:
  displayName: AWS EFS CSI Driver Operator
  description: Operator that installs and configures the CSI driver for Amazon Elastic File System (AWS EFS).
  keywords:
    - storage
    - efs
  links:
    - name: Documentation
      url: https://github.com/openshift/aws-efs-csi-driver-operator
    - name: Source Repository
      url: https://github.com/openshift/aws-efs-csi-driver-operator
  version: 4.9.0
  maturity: stable
  maintainers:
    - email: aos-storage-staff@redhat.com
      name: Red Hat
  minKubeVersion: 1.21.0
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: aws-efs-csi-driver-operator
    alm-status-descriptors: aws-efs-csi-driver-operator.v4.9.0
  selector:
    matchLabels:
      alm-owner-metering: aws-efs-csi-driver-operator
  installModes:
  - type: OwnNamespace
    supported: false
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
        - rules:
          - apiGroups:
            - ''
            resources:
            - pods
            - services
            - endpoints
            - events
            - configmaps
            - secrets
            verbs:
            - '*'
          - apiGroups:
            - apps
            resources:
            - deployments
            - daemonsets
            - replicasets
            verbs:
            - '*'
          - apiGroups:
            - monitoring.coreos.com
            resources:
            - servicemonitors
            verbs:
            - '*'
          serviceAccountName: aws-efs-csi-driver-operator
      clusterPermissions:
        - rules:
          - apiGroups:
            - security.openshift.io
            resourceNames:
            - privileged
            resources:
            - securitycontextconstraints
            verbs:
            - use
          - apiGroups:
            - operator.openshift.io
            resources:
            - clustercsidrivers
            verbs:
            - get
            - list
            - watch
            # The Config Observer controller updates the CR's spec
            - update
            - patch
          - apiGroups:
            - operator.openshift.io
            resources:
            - clustercsidrivers/status
            verbs:
            - get
            - list
            - watch
            - update
            - patch
          - apiGroups:
            - ''
            resourceNames:
            - extension-apiserver-authentication
            - aws-ebs-csi-driver-operator-lock
            resources:
            - configmaps
            verbs:
            - '*'
          - apiGroups:
            - rbac.authorization.k8s.io
            resources:
            - clusterroles
            - clusterrolebindings
            - roles
            - rolebindings
            verbs:
            - watch
            - list
            - get
            - create
            - delete
            - patch
            - update
          - apiGroups:
            - ''
            resources:
            - serviceaccounts
            verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          - apiGroups:
            - coordination.k8s.io
            resources:
            - leases
            verbs:
            - '*'
          - apiGroups:
            - ''
            resources:
            - secrets
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - ''
            resources:
            - persistentvolumes
            verbs:
            - create
            - delete
            - list
            - get
            - watch
            - update
            - patch
          - apiGroups:
            - ''
            resources:
            - persistentvolumeclaims
            verbs:
            - get
            - list
            - watch
            - update
          - apiGroups:
            - storage.k8s.io
            resources:
            - volumeattachments
            verbs:
            - get
            - list
            - watch
            - update
            - delete
            - create
            - patch
          - apiGroups:
            - storage.k8s.io
            resources:
            - volumeattachments/status
            verbs:
            - patch
          - apiGroups:
            - storage.k8s.io
            resources:
            - storageclasses
            - csinodes
            verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - '*'
            resources:
            - events
            verbs:
            - get
            - patch
            - create
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - storage.k8s.io
            resources:
            - csidrivers
            verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - cloudcredential.openshift.io
            resources:
            - credentialsrequests
            verbs:
            - '*'
          - apiGroups:
            - config.openshift.io
            resources:
            - infrastructures
            - proxies
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - authentication.k8s.io
            resources:
            - tokenreviews
            verbs:
            - create
          - apiGroups:
            - ""
            resources:
            - nodes
            verbs:
            - get
            - list
            - watch
          serviceAccountName: aws-efs-csi-driver-operator
      deployments:
        - name: aws-efs-csi-driver-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: aws-efs-csi-driver-operator
            template:
              metadata:
                annotations:
                  target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
                labels:
                  app: aws-efs-csi-driver-operator
              spec:
                serviceAccountName: aws-efs-csi-driver-operator
                containers:
                - name: aws-efs-csi-driver-operator
                  image: quay.io/openshift/origin-aws-efs-csi-driver-operator:latest
                  imagePullPolicy: IfNotPresent
                  args:
                    - "start"
                    - "-v=2"
                  env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: DRIVER_IMAGE
                      value: quay.io/openshift/origin-aws-efs-csi-driver:latest
                    - name: PROVISIONER_IMAGE
                      value: quay.io/openshift/origin-csi-external-provisioner:latest
                    - name: NODE_DRIVER_REGISTRAR_IMAGE
                      value: quay.io/openshift/origin-csi-node-driver-registrar:latest
                    - name: LIVENESS_PROBE_IMAGE
                      value: quay.io/openshift/origin-csi-livenessprobe:latest
                    - name: OPERATOR_NAME
                      value: aws-efs-csi-driver-operator
                    - name: KUBE_RBAC_PROXY_IMAGE
                      value: quay.io/openshift/origin-kube-rbac-proxy:latest
                  resources:
                    requests:
                      memory: 50Mi
                      cpu: 10m
                priorityClassName: system-cluster-critical
                nodeSelector:
                  node-role.kubernetes.io/master: ""
                tolerations:
                  - key: CriticalAddonsOnly
                    operator: Exists
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    effect: "NoSchedule"
